cubeCobraHostName/mp-rest/url=https://cubecobra.com

cubeOwner=adam
devCubeOwner=adam

quarkus.http.access-log.enabled=true

quarkus.http.cors=true
quarkus.http.cors.paths=/*
quarkus.http.cors.origins=https://pyramiddraft.xyz,https://dev.pyramiddraft.xyz
quarkus.http.cors.methods=GET,POST,PATCH,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin

quarkus.mongodb.database=MTGames
quarkus.mongodb.connection-string=${MONGO_CONNECTION:password}

google.oauth.client-id=346763937043-5n1404id5rp57prha5ltf2rik6u5qnu5.apps.googleusercontent.com
google.oauth.dev-mode=true

scryfallApi/mp-rest/url=https://api.scryfall.com
scryfall.max-search-pages=5

################################################################################################
################### DEV
################################################################################################

# cubeCobraHostName/mp-rest/url=http://localhost:3000

# cubeOwner=zach
# devCubeOwner=zach

# quarkus.http.access-log.enabled=true

# quarkus.http.cors=true
# quarkus.http.cors.paths=/*
# quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173
# quarkus.http.cors.methods=GET,POST,PATCH,PUT,DELETE,OPTIONS
# quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin

# quarkus.mongodb.database=MTGames
# quarkus.mongodb.connection-string=mongodb://localhost:27017

# google.oauth.client-id=346763937043-5n1404id5rp57prha5ltf2rik6u5qnu5.apps.googleusercontent.com
# google.oauth.dev-mode=true

# scryfallApi/mp-rest/url=https://api.scryfall.com
# scryfall.max-search-pages=5
