cubeOwner=adam
devCubeOwner=adam

quarkus.http.access-log.enabled=true

quarkus.http.cors=true
quarkus.http.cors.paths=/*
quarkus.http.cors.methods=GET,POST,PATCH,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin

quarkus.mongodb.database=MTGames

google.oauth.client-id=346763937043-5n1404id5rp57prha5ltf2rik6u5qnu5.apps.googleusercontent.com

scryfallApi/mp-rest/url=https://api.scryfall.com
scryfall.max-search-pages=5

# Comma-separated list of admin email addresses
admin.emails=
