cubeCobraHostName/mp-rest/url=http://localhost:3000

cubeOwner=zach
devCubeOwner=zach

quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173

quarkus.mongodb.connection-string=mongodb://localhost:27017

google.oauth.dev-mode=true

admin.emails=hitma1221@gmail.com
