cubeCobraHostName/mp-rest/url=https://cubecobra.com

quarkus.http.cors.origins=https://pyramiddraft.xyz,https://dev.pyramiddraft.xyz

quarkus.mongodb.connection-string=${MONGO_CONNECTION}

google.oauth.dev-mode=false

admin.emails=hitma1221@gmail.com
