version: '3'
services:
  back:
    image: 7b1d7e9b1644
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_CONNECTION=$MONGO_CONNECTION
    networks:
      - internal_network
  front:
    image: 54a932c87c51
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NG_CLI_ANALYTICS=false
    volumes:
      - /home/ec2-user/nginx-letsEncrypt.conf:/etc/nginx/conf.d/default.conf
      - /home/ec2-user/letsencrypt:/etc/letsencrypt
    networks:
      - internal_network


networks:
 internal_network:
   driver: bridge
# docker run -e MONGO_CONNECTION=$MONGO_CONNECTION -d -p 8080:8080 ef25