version: '3'
services:
  back:
    image: b6909bc364e3
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_CONNECTION=$MONGO_CONNECTION
    networks:
      - internal_network
  front:
    image: 2bf7d82987d9
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NG_CLI_ANALYTICS=false
        #volumes:
        # - /home/ec2-user/new/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal_network


networks:
 internal_network:
   driver: bridge
# docker run -e MONGO_CONNECTION=$MONGO_CONNECTION -d -p 8080:8080 ef25