name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust Java version as needed
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker Build and Publish to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.REPO_OWNER }} --password-stdin
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/magic-draft:${{ github.sha }} .
          docker push ghcr.io/${{ env.REPO_OWNER }}/magic-draft:${{ github.sha }}
